config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :parkings
  root 'parkings#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord
  belongs_to :user, optional: true
  validates_presence_of :parking_type, :start_at
  validates_inclusion_of :parking_type, in: ['guest', 'short-term', 'long-term']

  validate :validate_end_at_with_amount

  def validate_end_at_with_amount
    if end_at.present? && amount.blank?
      errors.add(:amount, 'There must be amount if there is end time')
    end

    if end_at.blank? && amount.present?
      errors.add(:end_at, 'There must be end time if there is amount')
    end
  end

  def duration
    (end_at - start_at) / 60
  end

  def calculate_amount
    # debug
    # puts '---'
    # puts parking_type
    # puts '---'

    factor = user.present? ? 50 : 100

    if amount.blank? && start_at.present? && end_at.present?
      if parking_type == 'long-term'
        self.amount = calculate_long_term_amount
      else
        self.amount = if duration <= 60
                        200
                      else
                        200 + ((duration - 60).to_f / 30).ceil * factor
                      end
      end
    end
  end

  def calculate_long_term_amount
    if amount.blank? && start_at.present? && end_at.present?
      days = (duration / 1440).floor
      min = duration % 1440

      if min <= 360 && min > 0
        days * 1600 + 1200
      elsif min == 0
        days * 1600
      else
        (days + 1) * 1600
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :parkings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  def new
    @parking = Parking.new
  end

  def create
    @parking = Parking.new(start_at: Time.now)
    if current_user
      @parking.parking_type = params[:parking][:parking_type]
      @parking.user = current_user
    else
      @parking.parking_type = 'guest'
    end
    @parking.save!

    redirect_to parking_path(@parking)
  end

  def show
    @parking = Parking.find(params[:id])
  end

  def update
    @parking = Parking.find(params[:id])
    @parking.end_at = Time.now
    @parking.calculate_amount

    @parking.save!

    redirect_to parking_path(@parking)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>
    <% if current_user %>
      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <%= link_to('Change Password', edit_registration_path(:user)) %>
    <% else %>
      <%= link_to('Sign Up', new_registration_path(:user)) %> |
      <%= link_to('Login', new_session_path(:user)) %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/parkings/new.html.erb
<h1>Full-Stack Parking Calculate</h1>
<%= form_for @parking do |f| %>
  <% if current_user %>
    <label><%= f.radio_button :parking_type, "short-term" %> Short Term</label>
    <label><%= f.radio_button :parking_type, "long-term" %> Long Term </label>
  <% else %>
    Common Rate
  <% end %>
  <p>
    <%= f.submit "Start" %>
  </p>
<% end %>

app/views/parkings/show.html.erb
<h1>Full-Stack Parking Calculate</h1>
<% if @parking.amount.present? %>
  <p>
    Rate Type: <%= @parking.parking_type %>
  </p>
  <p>
    From <%= @parking.start_at %> To <%= @parking.end_at %>
  </p>
  <p>
    During <%= @parking.duration %> minutes
  </p>
  <p>
    Total <%= number_to_currency(@parking.amount.to_f / 100, :unit => "$") %>
  </p>
  <p>
    <%= link_to "Continue", new_parking_path %>
  </p>
<% else %>
  <%= form_for @parking do |f| %>
    <p>
      <%= f.submit "End" %>
    </p>
  <% end %>
<% end %>